import { Configuration, OpenAIApi } from "openai";
import { NextResponse } from "next/server";

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

const config = new Configuration({
  apiKey: OPENAI_API_KEY,
});

const openai = new OpenAIApi(config);

export async function POST(req: Request) {
  console.log("here");

  const { text } = await req.json();
  const messages: any[] = [
    {
      role: "system",
      content:
        "You are AIdetector, a robot assistant on which helps identify if a text were likely generated by an AI. You will: - Analyse the user text - Identify the likelihood of the text were written by an AI and which keywords helped to identify it. - Return a JSON with the exact structure { likelihood (int 0 to 100), keywords [string] }",
    },
    { role: "user", content: text },
  ];

  try {
    const openAIResponse: string | any = await openai
      .createChatCompletion({
        model: "gpt-4",
        messages: messages,
      })
      .then((response) => response.data?.choices[0].message?.content);

    const regex = /{[^}]+}/g;
    const jsonString = openAIResponse.match(regex)?.[0];
    if (!jsonString) throw new Error("No JSON string found");
    const json = JSON.parse(jsonString);
    return NextResponse.json(json);
  } catch (err) {
    console.error(err);
  }
}
